### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by kspearrin** [brucedog/u2flib#10]
Can we expect an update to support .NET Core? I would like to use this library but cannot until it supports .NET Standard. You would likely have to drop the Bouncy Castle dependency.

https://docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries

Thanks!!

**Comment by brucedog** [comment]
Yes I plan on creating a .net core version of the U2F library.

**Comment by brucedog** [comment]
Hey Kyle,

I am closing this issue since there is now a .NET core version of the U2F library. The library can be found here https://github.com/brucedog/U2F_Core. I have ran the unit tests and both libraries produce the same authentication and security results. I have not got around to creating a demo web site but I plan to soon. Hope you enjoy and if you have any questions please let me know.


Thanks,
Bryce

**Comment by kspearrin** [comment]
Great! Thanks again.
